version: '3.4'

services:

  webclient:
    image: leitee/pandora.schoolmngr.webclient:prod
    container_name: schoolmngrwebclient
    ports:
      - 8080:80
    restart: always
    depends_on: 
      - webapi

  webapi:
    image: leitee/pandora.schoolmngr.webapi:dev
    container_name: schoolmngrwebapi
    build:
      context: .
      dockerfile: ../Pandora.NetCore.ApiHost/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SQLSERVER_NAME=mssqlserver
    ports:
      - 8090:80
    restart: always
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - mssqlserver
      - elasticsearch

  identity:
    image: leitee/pandora.schoolmngr.identity:dev
    container_name: schoolmngridentity
    build:
      context: .
      dockerfile: ../Pandora.NetCore.Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SQLSERVER_NAME=mssqlserver
    ports:
      - 8095:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - mssqlserver
      - elasticsearch

  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssqlserver
    environment:
      SA_PASSWORD: "Devadmin321"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"
    volumes:
      - mssqlserver-data:/var/opt/mssql

  elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
     container_name: elasticsearch
     environment:
      - node.name=nosql01
      - cluster.initial_master_nodes=nosql01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"    
     ulimits:
       memlock:
         soft: -1
         hard: -1
     ports:
      - "9200:9200"
      - "9300:9300"
     volumes:
       - elasticsearch-data:/usr/share/elasticsearch/data
     networks:
       - esnet

  kibana:
     image: docker.elastic.co/kibana/kibana:7.1.1
     container_name: kibana
     ports:
       - "5601:5601"
     depends_on:
       - elasticsearch
     networks:
       - esnet

networks:
  esnet:

volumes:
  mssqlserver-data:
  elasticsearch-data: